### ISSUE TITLE
Can a compromised encryption key be used maliciously

### ISSUE THREAD

**Issue by gaiterjones** [genecommerce/module-encryption-key-manager#62]
If an encryption key has already been compromised can it still be used for a malicious API attack? The adobe documentation is not clear on this, in your document you quote the sansec response:

_Important note: generating a new encryption key using this functionality does not invalidate the old key. We recommend manually updating the old key in app/etc/env.php to a new value rather than removing it._

If I manually change the old key i.e. both keys are in env.php - compromised key and newly generated key - old key  is 12345 I edit it to be xxx12345 and save. Does this "invalidate" any malicious use of this key?

If the Adobe update forces JWT to use the new key Is your module still required on a 2.4.7-p3 install

**Comment by convenient** [comment]
>If the Adobe update forces JWT to use the new key Is your module still required on a 2.4.7-p3 install

Adobe implemented the same fix as this module, which prevents the JWT being used with the old encryption key. That successfully prevents the old encryption key from making authenticated requests in that manner.

> Can a compromised encryption key be used maliciously

Aside from the JWT vector, I do not know of any other attack vectors. However that does not mean there are not any, it also assumes that no others will be added in the future or in any third party modules. We built this module with the worst case assumption that old keys were in the wild, and to do everything we could to secure the system. So the best thing to do is to invalidate your old key by making sure it is no longer present in the `env.php`.

> old key is 12345 I edit it to be xxx12345 and save. Does this "invalidate" any malicious use of this key?

That does invalidate it yes. Because it is no longer the same as it was before. So long as you invalidate it in an unpredictable way that cannot be guessed, that is the analogous as this modules implementation of invalidation https://github.com/genecommerce/module-encryption-key-manager?tab=readme-ov-file#binmagento-geneencryption-key-managerinvalidate

**Comment by gaiterjones** [comment]
@convenient Thankyou very much for your comments and for answering my questions, the info was very helpful. Could be useful to add them to the readme for other users.
