### ISSUE TITLE
Deal with tfa_ data

### ISSUE THREAD

**Issue by mpchadwick** [genecommerce/module-encryption-key-manager#8]
tfa_ tables also contain encrypted values. from what I was overhearing in Slack they are maybe even double-encrypted? (encrytped vlaue added to JSON then encrypted again). Just creating this issue to track this so this module can offer some solution for re-encrypting these.

**Comment by convenient** [comment]
@cjnewbs Proposed solution

- Base new command on https://github.com/genecommerce/module-encryption-key-manager/blob/master/Console/ReencryptColumn.php
- Strip out all handling for tables etc, only need `--force` because we're hardcoding the table and columns
- begin targeting `tfa_user_config`
- decrypt the value
    -  iterate through
        -  look at `secret` and re-encrypt
- reencrypt whole value
- need to display before/afters in CLI in similar format
- Try and keep the output similar
- Try and add a basic test in `test.sh`
